// MedicineCategoryDummy.js

export const categoryOptions = [
  { value: "analgesik", label: "Analgesik" },
  { value: "antibiotik", label: "Antibiotik" },
  { value: "antasida", label: "Antasida" },
  { value: "antidiabetes", label: "Antidiabetes" },
  { value: "antihipertensi", label: "Antihipertensi" },
  { value: "antihistamin", label: "Antihistamin" },
  { value: "antilipemik", label: "Antilipemik" },
  { value: "nsaid", label: "NSAID" },
  { value: "antiemetik", label: "Antiemetik" },
  { value: "bronkodilator", label: "Bronkodilator" },
  { value: "antidiare", label: "Antidiare" },
  { value: "suplemen", label: "Suplemen" },
  { value: "antidepresan", label: "Antidepresan" },
  { value: "antivirus", label: "Antivirus" },
  { value: "antigout", label: "Antigout" },
  { value: "kortikosteroid", label: "Kortikosteroid" },
  { value: "diuretik", label: "Diuretik" },
  { value: "antijamur", label: "Antijamur" },
  { value: "hormon", label: "Hormon" },
  { value: "antikoagulan", label: "Antikoagulan" },
  { value: "dekongestan", label: "Dekongestan" },
  { value: "antivertigo", label: "Antivertigo" },
  { value: "antipsikotik", label: "Antipsikotik" },
  { value: "antispasmodik", label: "Antispasmodik" },
  { value: "antikolinergik", label: "Antikolinergik" },
  { value: "antiepilepsi", label: "Antiepilepsi" },
  { value: "imunosupresan", label: "Imunosupresan" },
  { value: "antiparkinson", label: "Antiparkinson" },
  { value: "antituberkulosis", label: "Antituberkulosis" },
  { value: "antimalaria", label: "Antimalaria" },
  { value: "antiretroviral", label: "Antiretroviral" },
  { value: "antitrombotik", label: "Antitrombotik" },
  { value: "antiaritmia", label: "Antiaritmia" },
  { value: "antifibrinolitik", label: "Antifibrinolitik" },
  { value: "antikonvulsan", label: "Antikonvulsan" },
  { value: "antihemoroid", label: "Antihemoroid" },
  { value: "antiemetik", label: "Antiemetik" },
  { value: "antimigrain", label: "Antimigrain" },
  { value: "antiobesitas", label: "Antiobesitas" },
  { value: "antiosteoporosis", label: "Antiosteoporosis" },
  { value: "antipiretik", label: "Antipiretik" },
  { value: "antirematik", label: "Antirematik" },
  { value: "antiseptik", label: "Antiseptik" },
  { value: "antitusif", label: "Antitusif" },
  { value: "antiulkus", label: "Antiulkus" },
  { value: "antivenom", label: "Antivenom" },
  { value: "anxiolytic", label: "Anxiolytic" },
  { value: "astringen", label: "Astringen" },
  { value: "ekspektoran", label: "Ekspektoran" },
  { value: "hemostatik", label: "Hemostatik" },
  { value: "laksatif", label: "Laksatif" },
  { value: "mukolitik", label: "Mukolitik" },
  { value: "mydriatik", label: "Mydriatik" },
  { value: "narkotik", label: "Narkotik" },
  { value: "neuroleptik", label: "Neuroleptik" },
  { value: "nootropik", label: "Nootropik" },
  { value: "oksitosik", label: "Oksitosik" },
  { value: "parasimpatomimetik", label: "Parasimpatomimetik" },
  { value: "prokinetik", label: "Prokinetik" },
  { value: "simpatomimetik", label: "Simpatomimetik" },
  { value: "trankuilizer", label: "Trankuilizer" },
  { value: "vasodilatator", label: "Vasodilatator" },
  { value: "vasokonstriktor", label: "Vasokonstriktor" },
  { value: "antidota", label: "Antidota" },
  { value: "antiandrogen", label: "Antiandrogen" },
  { value: "antianemia", label: "Antianemia" },
  { value: "antiangiogenik", label: "Antiangiogenik" },
  { value: "antiarteosklerosis", label: "Antiarteosklerosis" },
  { value: "antibakterial", label: "Antibakterial" },
  { value: "antikoagulan", label: "Antikoagulan" },
  { value: "antidiuretik", label: "Antidiuretik" },
  { value: "antiemetik", label: "Antiemetik" },
  { value: "antifibrinolitik", label: "Antifibrinolitik" },
  { value: "antifungi", label: "Antifungi" },
  { value: "antiglaukoma", label: "Antiglaukoma" },
  { value: "antihelmintic", label: "Antihelmintic" },
  { value: "antihemoragik", label: "Antihemoragik" },
  { value: "antihiperlipidemik", label: "Antihiperlipidemik" },
  { value: "antihiperurisemia", label: "Antihiperurisemia" },
  { value: "antihistaminik", label: "Antihistaminik" },
  { value: "antihipotensi", label: "Antihipotensi" },
  { value: "antiinflamasi", label: "Antiinflamasi" },
  { value: "antikaker", label: "Antikaker" },
  { value: "antikolinesterase", label: "Antikolinesterase" },
  { value: "antileprosi", label: "Antileprosi" },
  { value: "antilipemik", label: "Antilipemik" },
  { value: "antimikotik", label: "Antimikotik" },
  { value: "antineoplastik", label: "Antineoplastik" },
  { value: "antioksidan", label: "Antioksidan" },
  { value: "antiparasit", label: "Antiparasit" },
  { value: "antiplatelet", label: "Antiplatelet" },
  { value: "antipsoriasis", label: "Antipsoriasis" },
  { value: "antipiretik", label: "Antipiretik" },
  { value: "antiprotozoa", label: "Antiprotozoa" },
  { value: "antipsikotik", label: "Antipsikotik" },
  { value: "antireumatik", label: "Antireumatik" },
  { value: "antispasmodik", label: "Antispasmodik" },
  { value: "antitrombin", label: "Antitrombin" },
  { value: "antitiroidal", label: "Antitiroidal" },
  { value: "antitoksin", label: "Antitoksin" },
  { value: "antitusif", label: "Antitusif" },
  { value: "analeptik", label: "Analeptik" },
  { value: "anestesi", label: "Anestesi" },
  { value: "ansiolitik", label: "Ansiolitik" },
  { value: "antialergi", label: "Antialergi" },
  { value: "antiaritmia", label: "Antiaritmia" },
  { value: "antiasma", label: "Antiasma" },
  { value: "antibiotik_topikal", label: "Antibiotik Topikal" },
  { value: "antiemetik_antivertigo", label: "Antiemetik dan Antivertigo" },
  { value: "antifibrilasi", label: "Antifibrilasi" },
  { value: "antiflatulen", label: "Antiflatulen" },
  { value: "antihelmintik", label: "Antihelmintik" },
  { value: "antihemoroid", label: "Antihemoroid" },
  { value: "antihipertiroid", label: "Antihipertiroid" },
  { value: "antihipoglikemik", label: "Antihipoglikemik" },
  { value: "antihipotiroid", label: "Antihipotiroid" },
  { value: "antiinfeksi", label: "Antiinfeksi" },
  { value: "antikolinergik_inhalasi", label: "Antikolinergik Inhalasi" },
  { value: "antikonsepsi", label: "Antikonsepsi" },
  { value: "antikonvulsan", label: "Antikonvulsan" },
  { value: "antimotilitas", label: "Antimotilitas" },
  { value: "antinyeri", label: "Antinyeri" },
  { value: "antiosteoporosis", label: "Antiosteoporosis" },
  { value: "antiparkinson", label: "Antiparkinson" },
  { value: "antipruritik", label: "Antipruritik" },
  { value: "antipsoriasis", label: "Antipsoriasis" },
  { value: "antiseboroik", label: "Antiseboroik" },
  { value: "antiseptik_oral", label: "Antiseptik Oral" },
  { value: "antispasmodik", label: "Antispasmodik" },
  { value: "antitrombotik", label: "Antitrombotik" },
  { value: "antitusif_ekspektoran", label: "Antitusif dan Ekspektoran" },
  { value: "antivertigo", label: "Antivertigo" },
  { value: "antiviral", label: "Antiviral" },
  { value: "bronkodilator_inhalasi", label: "Bronkodilator Inhalasi" },
  {
    value: "depresan_sistem_saraf_pusat",
    label: "Depresan Sistem Saraf Pusat",
  },
  { value: "dermatologik", label: "Dermatologik" },
  { value: "diuretik_osmotik", label: "Diuretik Osmotik" },
  { value: "emolien", label: "Emolien" },
  { value: "enzim_pencernaan", label: "Enzim Pencernaan" },
  { value: "hepatoprotektor", label: "Hepatoprotektor" },
  { value: "hipolipidemik", label: "Hipolipidemik" },
  { value: "imunomodulator", label: "Imunomodulator" },
  { value: "imunosupresan", label: "Imunosupresan" },
  { value: "kardiovaskuler", label: "Kardiovaskuler" },
  { value: "keratolik", label: "Keratolik" },
  { value: "kortikosteroid_inhalasi", label: "Kortikosteroid Inhalasi" },
  { value: "kortikosteroid_topikal", label: "Kortikosteroid Topikal" },
  { value: "mukolitik_ekspektoran", label: "Mukolitik dan Ekspektoran" },
  { value: "neuroprotektif", label: "Neuroprotektif" },
  { value: "obat_mata", label: "Obat Mata" },
  { value: "obat_telinga", label: "Obat Telinga" },
  { value: "pelemas_otot", label: "Pelemas Otot" },
  { value: "pelembab_kulit", label: "Pelembab Kulit" },
  { value: "pengganti_hormon", label: "Pengganti Hormon" },
  { value: "penyeimbang_elektrolit", label: "Penyeimbang Elektrolit" },
  { value: "progestogen", label: "Progestogen" },
  { value: "prokinetik", label: "Prokinetik" },
  {
    value: "stimulan_sistem_saraf_pusat",
    label: "Stimulan Sistem Saraf Pusat",
  },
  { value: "suplemen_mineral", label: "Suplemen Mineral" },
  { value: "suplemen_vitamin", label: "Suplemen Vitamin" },
  { value: "topikal_antiinflamasi", label: "Topikal Antiinflamasi" },
  { value: "vaksin", label: "Vaksin" },
  { value: "vasodilatator_koroner", label: "Vasodilatator Koroner" },
  { value: "vasodilatator_perifer", label: "Vasodilatator Perifer" },
  { value: "vitamin_a", label: "Vitamin A" },
  { value: "vitamin_b_complex", label: "Vitamin B Complex" },
  { value: "vitamin_c", label: "Vitamin C" },
  { value: "vitamin_d", label: "Vitamin D" },
  { value: "vitamin_e", label: "Vitamin E" },
  { value: "vitamin_k", label: "Vitamin K" },
  { value: "zinc_supplement", label: "Zinc Supplement" },
  { value: "antidiabetic", label: "Antidiabetic" },
  { value: "antidiarrheal", label: "Antidiarrheal" },
  { value: "antiglaucoma", label: "Antiglaucoma" },
  { value: "antihyperuricemic", label: "Antihyperuricemic" },
  { value: "antimalarial", label: "Antimalarial" },
  { value: "antispasmodic", label: "Antispasmodic" },
  { value: "antithrombotic", label: "Antithrombotic" },
  { value: "bronchodilator", label: "Bronchodilator" },
  { value: "calcium_supplement", label: "Calcium Supplement" },
  { value: "decongestant", label: "Decongestant" },
  { value: "erectile_dysfunction", label: "Erectile Dysfunction" },
  { value: "expectorant", label: "Expectorant" },
  { value: "iron_supplement", label: "Iron Supplement" },
  { value: "laxative", label: "Laxative" },
  { value: "muscle_relaxant", label: "Muscle Relaxant" },
  { value: "nasal_spray", label: "Nasal Spray" },
  { value: "omega_3", label: "Omega-3" },
  { value: "probiotic", label: "Probiotic" },
  { value: "statin", label: "Statin" },
  { value: "thyroid_hormone", label: "Thyroid Hormone" },
  { value: "topical_antibiotic", label: "Topical Antibiotic" },
  { value: "urinary_tract_health", label: "Urinary Tract Health" },
  { value: "other", label: "Other" },
];
